### PR TITLE
Game balance

### PR DESCRIPTION
**Pull request by vsinh14**
# Description

Balanced the game. This includes
Pets
Enemies
Weapon Values (damage, fire rate, ammo, reload time)
Enemy spawning list and mapgenerator 

Fixes / Closes # (issue)
https://github.com/UQcsse3200/2024-studio-1/issues/530
## Type of change

-[] Fixes game balance 
# How Has This Been Tested?
Gameplay Testing and all tests are passing 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by mblauberg — APPROVED** [review]
looks good

**Comment by TriNhan-Pham** [comment]
This branch has conflicts, please resolve them.

**Review by dhruvanil55 — APPROVED** [review]
Mellee weapon ranges are too big.

**Comment by vsinh14** [comment]
> This branch has conflicts, please resolve them.

Done

**Comment by vsinh14** [comment]
> Mellee weapon ranges are too big.

Done

**Review by CameronBadman — APPROVED** [review]
LGTM

**Review by dhruvanil55 — APPROVED** [review]
LGTM

**Comment by TriNhan-Pham** [comment]
LGTM

**Pull request merged**
