### PR TITLE
Team 1 menuimprovements

### PR DESCRIPTION
**Pull request by yashwanthg22**
# Description

This PR has an enable or disable option for the cutscene in the settings menu screen,  updated the player select screen by adding a text box for seed input and also added the event listener for esc button in most of the screens.

Fixes / Closes # (issue)
#483
#494 
#495 
#496 
# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Gameplay Testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by manya-k** [comment]
please describe what this pr is for?

**Review by IanP96 — CHANGES_REQUESTED** [review]
This has a lot of outdated code from main that has since been changed/removed. Please merge main into this branch (update it first). The only changes should be changes that you have made

**Review by AElanagai — CHANGES_REQUESTED** [review]
Please Edit the description template for PR, Thanks.

**Comment by Aryan-S-Gupta** [comment]
Womp Womp

**Comment by dhruvanil55** [comment]
The exit screen after you die is unable to be pressed only the esc key work s

**Review by IanP96 — CHANGES_REQUESTED** [review]
there is still a lot of outdated code that was changed in main

**Comment by vsinh14** [comment]
> there is still a lot of outdated code that was changed in main

Resolved

**Comment by vsinh14** [comment]
> The Seed isn't stored in the JSON file, so acts like a textbox right now

Resolved

**Comment by vsinh14** [comment]
> please describe what this pr is for?

Done

**Comment by vsinh14** [comment]
> This has a lot of outdated code from main that has since been changed/removed. Please merge main into this branch (update it first). The only changes should be changes that you have made

Main merged into branch

**Comment by yashwanthg22** [comment]
> The exit screen after you die is unable to be pressed only the esc key work s

fixed this issue.

**Pull request merged**
