### PR TITLE
Team 2 weapon

### PR DESCRIPTION
**Pull request by Magnius001**
- Improved melee weapon damaging mechanic
- Added directional weapon animation for melee and ranged weapons.

### CODE REVIEW

**Comment by Magnius001** [comment]
Bugs!

**Comment by Magnius001** [comment]
Fixed by changing event name of KeyboardPlayerInputComponent from "attack" to "attackMelee"

**Comment by vsinh14** [comment]
Please remove log files from your pull request please and thank you

**Comment by Magnius001** [comment]
> Please remove log files from your pull request please and thank you

Log files removed

**Pull request merged**
