### PR TITLE
Boss talk dialog

### PR DESCRIPTION
**Pull request by JigyasuMittal**
Added Dialog Boxes

### CODE REVIEW

**Comment by Aryan-S-Gupta** [comment]
image

Can you please fix the issue with z-index ? I fixed the offset and added the missing files for you, this is the only issue right now

**Review by Aryan-S-Gupta — CHANGES_REQUESTED** [review]
Also, please add suitable JavaDocs

**Comment by JigyasuMittal** [comment]
Please confirm if it is fixed now

**Review by Aryan-S-Gupta — APPROVED** [review]
Seems correct visually, I'll accept it

**Pull request merged**
