### PR TITLE
Items s4 merge into main

### PR DESCRIPTION
**Pull request by keagan-stoessel**
# Description
This feature ticket addresses the final adjustments and completion of previously implemented features, as well as resolving functionality gaps from the last sprint. It includes polishing key elements and ensuring that all items function as intended. Additionally, improvements were made to the builds so that the items spawned in the Enemy Room are unique to the character chosen.

Fixes / Closes # (issue)
#507 
#508 
#519
#347
#522 
#523 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?
- [x] Junit Testing
- [x] Visual Testing

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by vsinh14 — APPROVED** [review]
Changes seem good and work well

**Comment by CameronBadman** [comment]
LGTM

**Review by CameronBadman — COMMENTED** [review]
LGTM

**Review by CameronBadman — COMMENTED** [review]
LGTM

**Review by CameronBadman — APPROVED** [review]

**Pull request merged**
