### PR TITLE
Test room, refactored Levels to include a Manual Testing Environment.

### PR DESCRIPTION
**Pull request by SIN-Willett**
# Description

This PR brings in a new type of room: an armoury with one of each item.
and a TestLevel(Factory) that includes it.

There is also a refactor that makes Level, and MapGenerator into interfaces, with their original implementations moved into new classes.

Fixes / Closes # (issue)
- [x] #464 
- [x] #481

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] ~Breaking change (fix or feature that would cause existing functionality to not work as expected)~
- [x] ~This change requires a documentation update~

# How Has This Been Tested?

It is a test, it tests other things, mutual validation is used for testing these classes.

- [x] All of the Items that are generated by CollectibleFactory
- [x] All of the npcs that are generated by NPCFactory

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by notinclined — APPROVED** [review]
Reviewed code changes passed all tests

**Comment by CameronBadman** [comment]
@SIN-Willett maybe add the music?

**Review by CameronBadman — APPROVED** [review]
LGTM to me

**Comment by Magnius001** [comment]
Game crash when picking up the Ring of Fire in the test room.
image

And should the test level load in all weapons, or just the shotgun?

**Comment by SIN-Willett** [comment]
> Game crash when picking up the Ring of Fire in the test room. image
> 
> And should the test level load in all weapons, or just the shotgun?

It ideally should be all… but when I tried to do all of them the game crashed, I hoped you would add all the others in `WeaponFactory.getAllSpecs()`

**Comment by Magnius001** [comment]
Added other weapons, I left out the "fnscar" as I forgot the assets for it, which was causing the issue.

**Review by Magnius001 — APPROVED** [review]

**Comment by SIN-Willett** [comment]
> Added other weapons, I left out the "fnscar" as I forgot the assets for it, which was causing the issue.

Legend, thank you :)

**Comment by SIN-Willett** [comment]
@vsinh14 feel free to merge whenever you're happy with it, otherwise I'll just do it tonight :p

**Comment by SIN-Willett** [comment]
All remaining Sonarcloud issues are to do with RandomMapGenerator (which is all team 6 code, it's only showing up for this PR because I moved that code into a new file).

**Comment by vsinh14** [comment]
The animals in the second room are not within the room's bounding
The tombstone does not create a pet 
The divine potion crashes the game

**Review by vsinh14 — CHANGES_REQUESTED** [review]
The animals in the second room are not within the room's bounding
The tombstone does not create a pet
The divine potion crashes the game

**Comment by SIN-Willett** [comment]
> The animals in the second room are not within the room's bounding The tombstone does not create a pet The divine potion crashes the game

All 3 of these errors are within other people's code, This PR simply to create an environment where these errors can be easily tested for... the fact that known bugs are present is an indication of this feature WORKING AS INTENDED.

The longer we delay pulling this in, the less useful it will be to actually fix those bugs.

**Comment by SIN-Willett** [comment]
> The animals in the second room are not within the room's bounding
This is why team 7 was asked to merge their fix in... if that didn't fix it, then there is still a bug in their code.

> The tombstone does not create a pet

This is because Dog is missing animation parts, this is Team 7s responsibility to fix in another PR.

> The divine potion crashes the game

That is team 3's responsibility, if they want to fix this bug they can.

**Comment by vsinh14** [comment]
> > The animals in the second room are not within the room's bounding
> 
> This is why team 7 was asked to merge their fix in... if that didn't fix it, then there is still a bug in their code. (its  a map issue but team seven changes dont fix them even for your branch) 
> 
> > The tombstone does not create a pet
> 
> This is because Dog is missing animation parts, this is Team 7s responsibility to fix in another PR. (shall be tested)
> 
> > The divine potion crashes the game
> 
> That is team 3's responsibility, if they want to fix this bug they can.

**Review by vsinh14 — APPROVED** [review]
All issues are fixed and working as expected

**Pull request merged**
