### PR TITLE
Remove menu smells, how to play screen scales

### PR DESCRIPTION
**Pull request by IanP96**
# Description

Remove menu smells
- Comments
- Unused imports/methods/fields
- Make some public fields private

How to play screen scales better
- Uses word wrap
- Wrapping lines instead of paragraphs

No related issue

## Type of change

Please delete options that are not relevant.

- [x] Code smells

# How Has This Been Tested?

- [x] All unit tests still work
- [x] Applying/changing settings still works
- [x] Player selection and loading still works
- [x] How to play screen scales - try resizing the window, the text will wrap

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (no changes needed)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by IanP96** [comment]
@SIN-Willett have changed GameOptions a bit, could you confirm this is ok

**Comment by IanP96** [comment]
@TriNhan-Pham have changed the how to play screen for scaling

**Review by dhruvanil55 — APPROVED** [review]
LGTM - checked out the branch game works as intended.

**Review by dhruvanil55 — APPROVED** [review]
LGTM

**Pull request merged**
