### PR TITLE
Team 1 keybindings

### PR DESCRIPTION
**Pull request by sahajdeep31**
# Description

Implemented the key bindings to switch between different keys for player movement and shoot
Fixes / Closes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by TriNhan-Pham** [comment]
Tested the game with different keybinding settings, it worked and did not break anything. Should write tests to make sure everything works properly.

**Review by TriNhan-Pham — COMMENTED** [review]
Tested the game with different keybinding settings, it worked and did not break anything. Should write tests to make sure everything works properly.

**Review by IanP96 — CHANGES_REQUESTED** [review]
- It's possible to have both moveWithWASD and shootWithWASD set to true, which doesn't make much sense. Change it so that you either move with wasd or shoot with wasd but not both. same for arrow keys
- when you change the settings, apply them, then go back to the settings screen, the new settings aren't shown, just the default ones again.

**Review by vsinh14 — COMMENTED** [review]
Please add your task ticket idk what you're working on

**Comment by vsinh14** [comment]
Please resolve the comment + combine with your team and remake the PR

**Pull request closed without merging**
