### PR TITLE
New game area from main game area migration

### PR DESCRIPTION
**Pull request by AElanagai**
# Description

Migrated Front-End Primative methods from Main game area to game area to ensure better quality of main game area for testing purposes

Please delete options that are not relevant.

- [x] fixed the MainGameArea dealing with any type of front end, or asset type coding. 
- [ ] This change does not require a update to the current, but will need the addition of a new Page

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AElanagai** [comment]
The background music () was already in the game area where play music() has been migrated , I dont understand the difference  much need the respective team to review that .

**Comment by CameronBadman** [comment]
@AElanagai I checked the methods for any issues, they technically are Overide methods from the LoadedFactory, which GameArea extends to config itself by changing these `abstract` methods in LoadedFactory, just as long as they are in the GameArea, they shouldn't cause any functionality issues.

**Review by CameronBadman — CHANGES_REQUESTED** [review]
please make the methods overide the LoadedFactory methods for any of the getTectures or assets stuff

**Comment by AElanagai** [comment]
yeah the methods are overridden from their super class ones(loaded factory) , yet to just update the calling of display ui() either in maingamearea of game area? . I updated few methods that weren't .

**Pull request merged**
