### PR TITLE
Team 1 key bindings

### PR DESCRIPTION
**Pull request by sahajdeep31**
# Description

Updated the confirmation Dialog so user can select different keys for each controls.

Fixes / Closes # (issue)
#538 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by IanP96 — CHANGES_REQUESTED** [review]
You shouldn't allow the user to have WASD for both moving and shooting in the first place, the game breaks if you make the settings like this. You only need two options:
- move with WASD and shoot with arrows
- or shoot with WASD and move with arrows
You don't need four options like you currently have

**Review by keagan-stoessel — APPROVED** [review]
lgtm

**Comment by CameronBadman** [comment]
should you really allow the player to put both the shooting and movement controls together?

**Review by TriNhan-Pham — COMMENTED** [review]
Changes have been requested by Ian already, no more comment

**Comment by IanP96** [comment]
Closing for now, reopen once fixed

**Pull request closed without merging**
