### PR TITLE
Team 1 death screen statistics

### PR DESCRIPTION
**Pull request by sahajdeep31**
# Description

Updated the UI for better visibility of the text.

Fixes / Closes # (issue)
#541 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by TriNhan-Pham — CHANGES_REQUESTED** [review]
The game crashes when the player die, please review your code

**Comment by IanP96** [comment]
> The game crashes when the player die in the first room, please review your code

doesn't happen anymore, added a null check

**Review by IanP96 — APPROVED** [review]
Looks ok to me now, the game doesn't crash when you die and the score/coins are shown. Ideally more testing/review would be needed

**Review by TriNhan-Pham — APPROVED** [review]
LGTM now, should have more testings

**Pull request merged**
