### PR TITLE
Menu Improvements and Update How To Play Menu

### PR DESCRIPTION
**Pull request by TriNhan-Pham**
# Description

This PR has some small changes that increase visibility of the buttons and update the How To Play menu with new animals.

Fixes / Closes # (issue)
#528 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# How Has This Been Tested?

This has been tested manually and worked properly.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by justarandomnameduh — APPROVED** [review]
LGTM, changes doesn't affect the overall code base so no risk of ruining others.

**Review by vsinh14 — APPROVED** [review]
No functionality changes

**Comment by IanP96** [comment]
Screenshot 2024-10-16 alle 10 19 01 AM
HLTH, SPD, Enter seed labels aren't very visible now, could you fix this if you have time

**Comment by vsinh14** [comment]
Please change the how to play values to the correct ones in npcconfigs

**Comment by TriNhan-Pham** [comment]
> Please change the how to play values to the correct ones in npcconfigs

Done

**Comment by TriNhan-Pham** [comment]
> Screenshot 2024-10-16 alle 10 19 01 AM HLTH, SPD, Enter seed labels aren't very visible now, could you fix this if you have time

Done

**Pull request merged**
